### ISSUE TITLE
Add dehumidifer to config schema

### ISSUE THREAD

**Issue by kovapatrik** [kovapatrik/homebridge-midea-platform#26]
Currently only Air Conditioner is available when a user wants to add a device by IP. If I get it correctly the dehumidifer has exaclty the same options as the air conditioner or they have a large intersection of them.

@dkerr64 Can you please check if all settings are valid for a dehumidifer as for an AC?

**Comment by dkerr64** [comment]
Yes, this is my to-do.  I will update the schema.  And there are some settings that probably could go into the config, like min/max humidity range.

Thanks.

**Comment by dkerr64** [comment]
Just sent a PR that updates the schema.  Took quite a bit of work to make sure that the config file does not have options for AC in a dehumidifier section and vis-versa.  This required that all the settings become optional, so that they are not written to the config file by the schema editor.  I had to update the AC code to account that some settings may be undefined in the config file.  Please check that your AC device is working correctly.

I also created a README file with more complete documentation.  Again, please look at the AC section and update as you would like.
