### ISSUE TITLE
Mode selection on homekit

### ISSUE THREAD

**Issue by ramon-angosto** [kovapatrik/homebridge-midea-platform#51]
If it's possible i would like to have the option to select the Mode of the dehumidifier in Homekit. In Homekit under the dehumidifier target there is already a wheel with some options that i thing in some way they might be changed to the different modes, right now the options are automatic(only turns on), humidifier(does nothing), dehumidifier(same as automatic), and deactivate, stops  the dehumidifier.

I also seen in the logs that if i change the mode in the app it reads the value in homebridge, so the only thing missing I think it's creating this link somehow. I also have seen that the configuration already has the mode, defined.

If I have experience with this I will try to do it my self, but I don't know where to start, rather than copying one of the sliders and linking the positions to the modes, might not be the best approach.

Could some one implement that

**Comment by dkerr64** [comment]
The short answer is no.

The longer answer... I consider this a bug in the Apple Home user interface... it is presenting _auto_ and _humidify_ options to the user when it should not, because the user interface is not paying attention to the `validValues` for target state.  The HomeKit API has concept of current/target state, this can be humidify, dehumidify or auto.  Because this is a dehumidifier the only valid current/target state is dehumidifying or off/idle.  It is not valid for either to be humidifier.  To prevent errors being logged if Apple Home attempts to request the device to start humidifying, the plugin sets the only valid value as being dehumidifier.

Okay, so the user interface is ignoring that setting.  But under the covers it is not.  If you select auto or humidify then the UI accepts it, but immediately adjusts it to dehumidify and the plugin receives a request to turn on (or off) the dehumidifier.  The only values coming through to the plugin are 1 or 0 representing on or off.  The plugin is not receiving requests to set target state to auto/humidify/dehumidify because it can only ever be dehumidify, thus there is no way to know if the user selected _auto_, _humidify_ or _dehumidify_.

Could this be changed.  Maybe.  But it would likely open up a can of worms.  The plugin would have to register as both a humidifier and dehumidifier... changing what are considered `validValues` for current/target state.  In fact during development I had that, but then changed it because it caused other issues that caused error messages to log because the device is only a dehumidifier.

If you have a homebridge development environment and want to have a go...

- Make it user configurable by adding a setting to device specific config.
- When selected, change the valid values for TargetHumidifierDehumidifierState [here](https://github.com/kovapatrik/homebridge-midea-platform/blob/39510bc262b6c87e0411a833876a719af761ffe4/src/accessory/DehumidifierAccessory.ts#L49)
- Update the target state handler for [set](https://github.com/kovapatrik/homebridge-midea-platform/blob/39510bc262b6c87e0411a833876a719af761ffe4/src/accessory/DehumidifierAccessory.ts#L222)
- Not sure what you should do with the target state handler for [get](https://github.com/kovapatrik/homebridge-midea-platform/blob/39510bc262b6c87e0411a833876a719af761ffe4/src/accessory/DehumidifierAccessory.ts#L212), this is the can-of-worms.  I don't know how HomeKit will behave if this always returns dehumidifying (as it should).
- More can-of-worms likely in current state handler for [get](https://github.com/kovapatrik/homebridge-midea-platform/blob/39510bc262b6c87e0411a833876a719af761ffe4/src/accessory/DehumidifierAccessory.ts#L182), as it probably does need to pretend to be humidifying when it is not if you want the Apple Home user interface to show the state as humidifying (when it is not).

I think you are trying to fit a square peg in a round hole and in my opinion it is not worth trying.

**Comment by dkerr64** [comment]
I recommend closing this issue as not planned.  iOS 17.2 fixes the bug so auto and humidify options will not show any more.
