### ISSUE TITLE
Refresh rate or something else

### ISSUE THREAD

**Issue by tso33** [kovapatrik/homebridge-midea-platform#9]
I have a problem with my automation and the display off feature.

I set a HomeKit automation when the display comes on Then wait seven seconds and turn it off.

But sometimes I use fan mode from the AC remote. The HomeKit ac status takes some time to refresh and when refreshed (AC on and display on) the automation doesn't work..

**Comment by kovapatrik** [comment]
Currently the plugin refreshes the status in every 30 seconds. I can lower that to 10 or something like that.

But I'm not sure if I understand the problem. Does the remote turns on the display and that's why your automation breaks?

**Comment by tso33** [comment]
It doesn't break, just doesn't work and I don't understand why. Normally it must turned off after 7 seconds. The only difference is that I controlled the ac from remote

**Comment by kovapatrik** [comment]
But can you control your AC after you use the remote or that doesn't work as well? Because if you can control, then I don't know what can go wrong in the automation except if the state is out of sync.

I can add it as a config, but 1 second is too fast. I have to send and wait to get a response from the AC then parse the message. I think 5 seconds can work.
